[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_HTTP_PORTS = "$PORT"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"
